### ISSUE TITLE
Missing Images on steering-committee

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/science.eclipse.org#23]
**Describe the bug**
Go to https://science.eclipse.org/about/steering-committee/ 

The last 2 images are missing. If we don't have the images, let's use the default gray image. If we do have them, we should add them.

**Comment by chrisguindon** [comment]
+1 we can use their images from their Eclipse profile:

- https://accounts.eclipse.org/users/tmiranda
- https://accounts.eclipse.org/users/tresheim
