### ISSUE TITLE
Hugo website is ready for primetime

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/science.eclipse.org#7]
I received a note from Torkild saying that the site is ready to be on production! We now need to deploy this site on openshift and point science.eclipse.org to this new website!

I will start by creating up the initial configurations and I will let my colleague, @mbarbero finalize the process!

**Comment by chrisguindon** [comment]
@mbarbero I added the Jenkins file with k8s configurations to the repo. 

I also created a Jenkins instance. 

Please let me know if you need anything else from me!

**Comment by mbarbero** [comment]
I've deployed the website on the cluster and created a patch for the reverse proxy configuration. As soon as it is merged and applied by puppet, it should be live.

**Comment by mbarbero** [comment]
I've just submitted the patch for the reverse proxy configuration. It should be avail. in the next couple of hours.

**Comment by chrisguindon** [comment]
The new website is on production! 
https://science.eclipse.org/

Thanks @mbarbero
